clc;
clear;
close all;
%风玫瑰图
%% 数据准备
% 读取数据
load data.mat
D = direction;
S = speed;

%% 风玫瑰图绘制
map = colormap(nclCM(355)); %color包里选颜色
close all;
Options = {'anglenorth',0,...
           'angleeast',90,...
           'labels',{'N (0°)','NE (45°)','E (90°)','SE (135°)','S (180°)','SW (225°)','W (270°)','NW (315°)'},...
           'freqlabelangle','auto',...
           'nspeeds',7,...
           'ndirections',18,...
           'lablegend','Wind speeds in m/s',...
           'legendtype',2,...
           'legendvariable','W_s',...
           'min_radius',0.1,...
           'titlestring','Wind Rose Plot',...
           'height',12*50,...
           'width',15*50,...
           'cmap',map};
figureHandle = WindRose(D,S,Options);
