function colorbar_k2dt(mode,Z1,map1,Z2,map2)
% mode   - set position of colorbar, 'right' or 'bottom'
% Z1     - feature1 matrix
% map1   - colormap of feature1
% Z2     - feature2 matrix
% map2   - colormap of feature2

switch mode
    case 'right'
        % 右侧添加颜色条，设为不可见
        cb = colorbar('eastoutside');
        set(cb,'Visible','off')

        % 绘制颜色条1
        axes('Position',[0.85,0.62,0.037,0.25]);
        nLevels = size(map1,1);
        xData = [zeros(2, nLevels); 1.5*ones(2, nLevels)];
        yData = [linspace(0, nLevels-1, nLevels); linspace(1, nLevels, nLevels); ...
            linspace(1, nLevels, nLevels); linspace(0, nLevels-1, nLevels)];
        patch('XData', xData, 'YData', yData, ...
            'EdgeColor', 'none', ...
            'FaceColor', 'flat', ...
            'FaceVertexCData', map1)
        set(gca, 'YAxisLocation','right', ...
            'xtick',[],...
            'YLim',[min(yData(:)) max(yData(:))],...
            'YTick',[min(yData(:)) max(yData(:))],...
            'YTickLabel',{[min(Z1(:)) max(Z1(:))]})
        set(gca,'FontName', 'Arial', 'FontSize', 10)
        % 绘制颜色条2
        axes('Position',[0.85,0.16,0.037,0.25]);
        nLevels = size(map2,1);
        yData = [linspace(0, nLevels-1, nLevels); linspace(1, nLevels, nLevels); ...
            linspace(1, nLevels, nLevels); linspace(0, nLevels-1, nLevels)];
        xData = [zeros(2, nLevels); 1.5*ones(2, nLevels)];
        patch('XData', xData, 'YData', yData, ...
            'EdgeColor', 'none', ...
            'FaceColor', 'flat', ...
            'FaceVertexCData', map2)
        set(gca, 'YAxisLocation','right', ...
            'xtick',[],...
            'YLim',[min(yData(:)) max(yData(:))],...
            'YTick',[min(yData(:)) max(yData(:))],...
            'YTickLabel',{[min(Z2(:)) max(Z2(:))]})
        set(gca,'FontName', 'Arial', 'FontSize', 10)

    case 'bottom'
        % 底部添加颜色条，设为不可见
        cb = colorbar('southoutside');
        set(cb,'Visible','off')

        % 绘制颜色条1
        axes('Position',[0.2,0.15,0.25,0.04]);
        nLevels = size(map1,1);
        xData = [linspace(0, nLevels-1, nLevels); linspace(1, nLevels, nLevels); ...
            linspace(1, nLevels, nLevels); linspace(0, nLevels-1, nLevels)];
        yData = [zeros(2, nLevels); 1.5*ones(2, nLevels)];
        patch('XData', xData, 'YData', yData, ...
            'EdgeColor', 'none', ...
            'FaceColor', 'flat', ...
            'FaceVertexCData', map1)
        set(gca, 'XAxisLocation','bottom', ...
            'ytick',[],...
            'XLim',[min(xData(:)) max(xData(:))],...
            'XTick',[min(xData(:)) max(xData(:))],...
            'XTickLabel',{[min(Z1(:)) max(Z1(:))]})
        set(gca,'FontName', 'Arial', 'FontSize', 10)
        % 绘制颜色条2
        axes('Position',[0.6,0.15,0.25,0.04]);
        nLevels = size(map2,1);
        xData = [linspace(0, nLevels-1, nLevels); linspace(1, nLevels, nLevels); ...
            linspace(1, nLevels, nLevels); linspace(0, nLevels-1, nLevels)];
        yData = [zeros(2, nLevels); 1.5*ones(2, nLevels)];
        patch('XData', xData, 'YData', yData, ...
            'EdgeColor', 'none', ...
            'FaceColor', 'flat', ...
            'FaceVertexCData', map2)
        set(gca, 'XAxisLocation','bottom', ...
            'ytick',[],...
            'XLim',[min(xData(:)) max(xData(:))],...
            'XTick',[min(xData(:)) max(xData(:))],...
            'XTickLabel',{[min(Z2(:)) max(Z2(:))]})
        set(gca,'FontName', 'Arial', 'FontSize', 10)
end
end